### ISSUE TITLE
проблеми

### ISSUE THREAD

**Issue by ipiwebtech** [DenysTabachuk/Jupiter_flex_site#1]
хедер не збільшується під збільшений обсяг вмісту
<img width="949" alt="хедер" src="https://github.com/DenysTabachuk/Jupiter_flex_site/assets/129291207/b1b68969-e563-4224-a635-4ead6ecdadb3">

**Comment by ipiwebtech** [comment]
з меню в хедері те саме

**Comment by ipiwebtech** [comment]
а футер нормально розтягується, тут ок

Персональний сайт Табачук Дениса - ви не жінка, у вас прізвище відмінюється "Табачука"

**Comment by DenysTabachuk** [comment]
Добрий день, здається виправив. З фамілією прикра друкарська помилка.
